spring:
  profiles:
    active: @profileActive@
  config:
    import: optional:classpath:application/${spring.profiles.active}/,optional:classpath:application/${spring.profiles.active}/application-local.yml
